name: job_scraper 
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create database
        run: python create_db.py

      - name: Run RemoteOK scraper 
        run: python remote_scraper.py

      - name: Run WWR scraper
        run: python wwr_scraper.py